spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/InkLink_db
spring.datasource.username=InkLink
spring.datasource.password=Inklink2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true